import { mazzard, move_x, neueMachina, ttOctosquares } from "./ui/fonts";

import "@/app/ui/reset.scss";
import "@/app/ui/global.scss"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${mazzard.variable} ${neueMachina.variable} ${ttOctosquares.variable} ${move_x.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
